# Project parameters.
export SRCDIR    ::= ./src
export TESTDIR   ::= ./test
export DOCSDIR   ::= ./docs
export SCRIPTDIR ::= ./script

# Installation parameters.
export prefix      ?= /usr/local
export exec_prefix ?= $(prefix)
export bindir      ?= $(exec_prefix)/bin
export libexecdir  ?= $(exec_prefix)/libexec
export libdir      ?= $(prefix)/lib
export datarootdir ?= $(prefix)/share
export mandir      ?= $(datarootdir)/man


########################################################################
#                                BUILD
########################################################################

.PHONY: build
build: man

# Generate ROFF format man pages.
#   from: $(SRCDIR)/man/*.ronn
#   to:   $(SRCDIR)/man/*
.PHONY: man
man: $(patsubst %.ronn,%,$(wildcard $(SRCDIR)/man/*.ronn)) ;

$(SRCDIR)/man/%: $(SRCDIR)/man/%.ronn
	ronn --warnings --roff '$<'

# Delete files generated by `build'.
.PHONY: clean
clean:
	-rm '$(patsubst %.ronn,%,$(wildcard $(SRCDIR)/man/*.ronn))'


########################################################################
#                                CHECK
########################################################################

.PHONY: check
check:
	bats '$(TESTDIR)'


########################################################################
#                                 DOCS
########################################################################

.PHONY: docs
docs: docs-man docs-img

# Generate HTML format man pages.
#   from: $(SRCDIR)/man/*.ronn
#   to:   $(DOCSDIR)/man/*.html
.PHONY: docs-man
docs-man: $(patsubst $(SRCDIR)/man/%.ronn,\
	             $(DOCSDIR)/man/%.html,\
	             $(wildcard $(SRCDIR)/man/*.ronn)) ;

$(DOCSDIR)/man/%.html: $(SRCDIR)/man/%.ronn
	ronn --warnings --html '$<'
	mv '$(<:.ronn=.html)' '$(DOCSDIR)/man'

# Rasterise HTML pages and save them in PNG format.
#   from: $(DOCSDIR)/src/*.html
#   to:   $(DOCSDIR)/img/*.png
.PHONY: docs-img
docs-img: $(patsubst $(DOCSDIR)/src/%.html,\
	             $(DOCSDIR)/img/%.png,\
	             $(wildcard $(DOCSDIR)/src/*.html)) ;

$(DOCSDIR)/img/%.png: $(DOCSDIR)/src/%.html
	phantomjs '$(SCRIPTDIR)/capture.js' '$<' '$@'

# Delete files generated by `docs'.
.PHONY: docs-clean
docs-clean:
	# Delete generated HTML format man pages (docs-man).
	-rm '$(patsubst $(SRCDIR)/man/%.ronn,$(DOCSDIR)/man/%.html,\
	                $(wildcard $(SRCDIR)/man/*.ronn))'

	# Delete generated PNG images (docs-img).
	-rm '$(patsubst $(DOCSDIR)/src/%.html,$(DOCSDIR)/img/%.png,\
	                $(wildcard $(DOCSDIR)/src/*.html))'


########################################################################
#                               INSTALL
########################################################################

.PHONY: install
install: install-params install-files install-update

# Display parameters used.
.PHONY: install-params
install-params:
	@echo '-> Parameters'; \
	vars=(DESTDIR prefix exec_prefix bindir libexecdir libdir datarootdir \
	      mandir); \
        for var in "$${vars[@]}"; do \
	  printf '  %-11s = %s\n' "$${var}" "$${!var}"; \
	done; \
	echo

# Install program files.
.PHONY: install-files
install-files:
	@echo '-> Installing files'

#	Install executables.
#	  from: $(SRCDIR)/bin/*
#	  to  : $(DESTDIR)$(bindir)/*
	@for src in '$(SRCDIR)/bin'/*; do \
	  src_file="$$(basename "$${src}")"; \
	  dst='$(DESTDIR)$(bindir)/'"$${src_file}"; \
	  echo "  $${dst}"; \
	  install -Dm755 "$${src}" "$${dst}"; \
	done

#	Install internal executables (recursively).
#	  from: $(SRCDIR)/libexec/*
#	  to  : $(DESTDIR)$(libexecdir)/*
	@src_base='$(SRCDIR)/libexec'; \
	IFS=$$'\n'; \
	for src in $$(find "$${src_base}" -type f); do \
	  dst='$(DESTDIR)$(libexecdir)'"$${src#$${src_base}}"; \
	  echo "  $${dst}"; \
	  install -Dm755 "$${src}" "$${dst}"; \
	done

#	Install libraries (recursively).
#	  from: $(SRCDIR)/lib/*
#	  to:   $(DESTDIR)$(libdir)/*
	@src_base='$(SRCDIR)/lib'; \
	IFS=$$'\n'; \
	for src in $$(find "$${src_base}" -type f); do \
	  dst='$(DESTDIR)$(libdir)'"$${src#$${src_base}}"; \
	  echo "  $${dst}"; \
	  install -Dm644 "$${src}" "$${dst}"; \
	done

#	Install man pages.
#	  from: ./$(SRCDIR)/man/*.[0-9]
#	  to:   $(DESTDIR)$(mandir)/*.[0-9]
	@for src in '$(SRCDIR)/man'/*.[0-9]; do \
	  src_file="$$(basename "$${src}")"; \
	  dst='$(DESTDIR)$(mandir)/man'"$${src_file: -1}/$${src_file}"; \
	  echo "  $${dst}"; \
	  install -Dm644 "$${src}" "$${dst}"; \
	done

# Update installed files.
.PHONY: install-update
install-update:
	@echo '-> Updating files' \

#	Update launcher paths.
	@file='$(DESTDIR)$(bindir)/varrick'; \
	echo "  $$file"; \
	sed -r -e '/^_d8e1_BIN_DIR=".*"$$/ d' \
	       -e 's;^(export _d8e1_LIB_DIR)=".*"$$;\1='\''$(libdir)/varrick'\'';' \
	       -e 's;^(export _d8e1_LIBEXEC_DIR)=".*"$$;\1='\''$(libexecdir)/varrick'\'';' \
	    -i "$$file"


########################################################################
#                                 HELP
########################################################################

define HELP_TEXT =
TARGETS:

  For packagers:
    build    build application
    install  install application
    check    run test suite
    clean    delete generated files
    help     display this help

  For developers:
    man      generate ROFF format man pages (build-time)
    docs     generate HTML format man pages and images (after editing man pages)


ENVIRONMENT:

  For packagers:
    The following variables customise installation. Their meaning is described
    in the GNU Make manual. [1] [2]

      DESTDIR     = /
      prefix      = /usr/local
      exec_prefix = $$(prefix)
      bindir      = $$(exec_prefix)/bin
      libexecdir  = $$(exec_prefix)/libexec
      libdir      = $$(prefix)/lib
      datarootdir = $$(prefix)/share
      mandir      = $$(datarootdir)/man


EXAMPLES:

  Build, and then install execuatables in `/usr/bin' and `/usr/lib/varrick',
  libraries in `/usr/lib/varrick' and man pages in `/usr/share/man'.

    $$ make build
    $$ make prefix='/usr' \ 
           libexecdir='/usr/lib' \ 
           install


REFERENCES:

  [1]: http://www.gnu.org/software/make/manual/make.html#Directory-Variables
  [2]: http://www.gnu.org/software/make/manual/make.html#DESTDIR

endef
export HELP_TEXT
.PHONY: help
help:
	@echo "$${HELP_TEXT}"
